### PR TITLE
make copy&paste work when entering token

### PR DESCRIPTION
**Pull request by dindom999**

### CODE REVIEW

**Comment by dindom999** [comment]
Hi jeffkowalski, I am using arch+i3, pasted from clipboard fail, so I change it. I will test it later in ubuntu.

**Comment by jeffkowalski** [comment]
@dindom999 - did you re-test?  What did you find?

**Comment by dindom999** [comment]
hi @jeffkowalski , I have changed back to getpass. sorry to make things mass.

**Comment by jeffkowalski** [comment]
Thank you, @dindom999 
I've merged into 2.0.15

**Pull request closed without merging**
