### PR TITLE
Date selection in search command

### PR DESCRIPTION
**Pull request by jaguarondi**
This fixes the date selection in the search command. There is still one caveat, the API doesn't seem to care about the user.timezone attribute, so requests using localtime are handled with GMT-7 or something like that. So I used UTC requests for now based on the system timezone. Which means that if you travel, the search will shift by the timezone difference. The way to go is to always use the default timezone saved in user.timezone. I'll wait for Evernote to reply to this on the forum before trying to revert the timezone difference from the timezone ID.

### CODE REVIEW

**Comment by jeffkowalski** [comment]
@jaguarondi unfortunately, the build is failing with these new changes.
You may have to adjust the test files to accommodate the different expected output.

If you haven't already done so, you might want to enable TravisCI builds on your own repo, which would enable you to confirm good build results before issuing a pull request.  It's really easy to setup TravisCI:  just go to https://travis-ci.org/, sign up using your github account (it's free), and click the switch to enable automated builds of your geeknote repo.  
The .travis.yml file already in the repo should be generic enough to work for your builds right out of the box.

Let me know if you need help.

**Comment by jaguarondi** [comment]
What should I do to run the same tests locally as Travis-CI does? I've nearly no experience with tests. I tried `python setup.py test`and `tox`but they do different things and none works (OSX). Is Travis-CI using the same tests?

Thanks

```
david@db-mbp geeknote $ python setup.py test
/usr/local/lib/python2.7/site-packages/setuptools/dist.py:285: UserWarning: Normalizing '0.2a' to '0.2a0'
  normalized_version,
running test
running egg_info
writing pbr to geeknote.egg-info/pbr.json
writing requirements to geeknote.egg-info/requires.txt
writing geeknote.egg-info/PKG-INFO
writing top-level names to geeknote.egg-info/top_level.txt
writing dependency_links to geeknote.egg-info/dependency_links.txt
writing entry points to geeknote.egg-info/entry_points.txt
reading manifest file 'geeknote.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files found matching '*.orig'
warning: no previously-included files found matching '*.pyc'
writing manifest file 'geeknote.egg-info/SOURCES.txt'
running build_ext

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
david@db-mbp geeknote $ tox
GLOB sdist-make: /Users/david/tmp/apps-src/geeknote/setup.py
py26 create: /Users/david/tmp/apps-src/geeknote/.tox/py26
py26 inst: /Users/david/tmp/apps-src/geeknote/.tox/dist/geeknote-0.2a0.zip
py26 installed: argparse==1.3.0,beautifulsoup4==4.4.1,evernote==1.25.1,geeknote==0.2a0,html2text==2015.6.21,httplib2==0.9.2,markdown2==2.3.0,oauth2==1.9.0.post1,SQLAlchemy==1.0.8,thrift==0.9.3,wheel==0.24.0
py26 runtests: PYTHONHASHSEED='3656314080'
py26 runtests: commands[0] | py.test
ERROR: InvocationError: could not find executable 'py.test'
py27 create: /Users/david/tmp/apps-src/geeknote/.tox/py27
py27 inst: /Users/david/tmp/apps-src/geeknote/.tox/dist/geeknote-0.2a0.zip
py27 installed: beautifulsoup4==4.4.1,evernote==1.25.1,geeknote==0.2a0,html2text==2015.6.21,httplib2==0.9.2,markdown2==2.3.0,oauth2==1.9.0.post1,SQLAlchemy==1.0.8,thrift==0.9.3,wheel==0.24.0
py27 runtests: PYTHONHASHSEED='3656314080'
py27 runtests: commands[0] | py.test
ERROR: InvocationError: could not find executable 'py.test'
____________________________________________ summary _____________________________________________
ERROR:   py26: commands failed
ERROR:   py27: commands failed
```

**Comment by jeffkowalski** [comment]
Sorry you're having trouble @jaguarondi 
I'm not terribly familiar with OSX, but I'll try to help.

First, you'll need to be sure you have pytest installed.  For me on Linux, this looks like:
```
$ sudo apt-get install python-pytest
$ py.test --version
This is py.test version 2.5.1, imported from /usr/lib/python2.7/dist-packages/pytest.pyc
```

From the looks of the dump you pasted, it seems you don't have pytest.  Maybe on OSX you might use something like
```
$ pip install -U pytest # or
$ easy_install -U pytest
```

Next, you'll want to be sure there aren't any stale byte-compiled files around.  This has bit me in the past, so it may be helpful to do this in the `geeknote` directory:
```
$ find . -name \*.pyc -exec rm \{\} \;
```

To run the tests from the top-most geeknote directory, you need only invoke 
```
$ py.test
```

Travis CI runs py.test as part of its build procedure, as defined in ```.travis.yml```
(Actually it runs the command ```env EDITOR=/bin/cat py.test```, so that the default editor it uses during one of the tests isn't interactive and stuck waiting for user input.)

Remember that switching Travis CI on (as I described above) will test your pushes to your own repo on a Linux machine automatically.

Hope this helps.

**Comment by jaguarondi** [comment]
Thanks, I didn't have pytest installed. `pip install pytest`did it.

I checked out your master branch and there are 7 tests already failing:
tests/test_out.py ..F..FFFFF...F...

Is that the case on your side also? They are related to date so I should be
able to fix this.

**Comment by jeffkowalski** [comment]
I do see one error locally (which I strangely don't see on Travis):

First, get the master branch (with a specific commit, so we're talking about the same one):
```
$ git clone --branch=master https://github.com/jeffkowalski/geeknote.git 
$ cd geeknote
$ git checkout -qf 830ec3bdbdf97cc8d272a02ff725faefd88453bf     
```

Then running tests, skipping the "manual" editor like vi or emacs
```
$ env EDITOR=/bin/cat py.test
```

yields

```
========================================================= test session starts ==========================================================
platform linux2 -- Python 2.7.6, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /home/jeff/tmp/geeknote, inifile: 
collected 96 items 

tests/test_argparser.py ..............
tests/test_editor.py ......
tests/test_gclient.py ..
tests/test_geeknote.py ....F.
tests/test_gnsync.py ....
tests/test_out.py .................
tests/test_storage.py ...................................
tests/test_tools.py ............

=============================================================== FAILURES ===============================================================
______________________________________________________ testNotes.test_parseInput1 ______________________________________________________

self = <test_geeknote.testNotes testMethod=test_parseInput1>

    def test_parseInput1(self):
        testData = self.notes._parseInput("title", "test body", "tag1", None, None, ["res 1", "res 2"])
        self.assertTrue(isinstance(testData, dict))
        if not isinstance(testData, dict):
            return
    
        self.assertEqual(testData['title'], "title")
        self.assertEqual(testData['content'], Editor.textToENML("test body"))
        self.assertEqual(testData["tags"], ["tag1", ])
>       self.assertEqual(testData["resources"], ["res 1", "res 2"])
E       AssertionError: None != ['res 1', 'res 2']

tests/test_geeknote.py:37: AssertionError
================================================= 1 failed, 95 passed in 6.02 seconds ==================================================
```

**Comment by jaguarondi** [comment]
Strange, here's the output for me. Anyway, I'll have a look at it.

```
david@db-mbp geeknote $ git checkout -f 830ec3bdbdf97cc8d272a02ff725faefd88453bf
HEAD is now at 830ec3b... Remove python2.6 from tox matrix
david@db-mbp geeknote $ env EDITOR=/bin/cat py.test
====================================== test session starts =======================================
platform darwin -- Python 2.7.10, pytest-2.8.2, py-1.4.30, pluggy-0.3.1
rootdir: /Users/david/tmp/apps-src/geeknote, inifile:
collected 96 items

tests/test_argparser.py ..............
tests/test_editor.py ......
tests/test_gclient.py ..
tests/test_geeknote.py ......
tests/test_gnsync.py ....
tests/test_out.py ..F..FFFFF...F...
tests/test_storage.py ...................................
tests/test_tools.py ............

============================================ FAILURES ============================================
____________________________ outTestsWithHackedStdout.test_print_date ____________________________

self = <test_out.outTestsWithHackedStdout testMethod=test_print_date>

    def test_print_date(self):
>       self.assertEquals(printDate(1095292800000), '2004-09-16')
E       AssertionError: '2004-09-15' != '2004-09-16'

tests/test_out.py:185: AssertionError
_________________ outTestsWithHackedStdout.test_print_list_with_selector_success _________________

self = <test_out.outTestsWithHackedStdout testMethod=test_print_list_with_selector_success>

    def test_print_list_with_selector_success(self):
        out.rawInput = lambda x: 2
        notes_list = '''=================== test ==================
    Found 2 items
      1 : 2004-09-16        2004-09-16        testnote
      2 : 2004-09-16        2004-09-16        testnote
      0 : -Cancel-\n'''
        out.printList([NoteStub() for _ in xrange(2)], title='test', showSelector=True)
        sys.stdout.seek(0)
>       self.assertEquals(sys.stdout.read(), notes_list)
E       AssertionError: '=================== test ==================\nFound 2 items\n  1 : 2004-09-15        2004-09-15        testnote\n  2 : 2004-09-15        2004-09-15        testnote\n  0 : -Cancel-\n' != '=================== test ==================\nFound 2 items\n  1 : 2004-09-16        2004-09-16        testnote\n  2 : 2004-09-16        2004-09-16        testnote\n  0 : -Cancel-\n'

tests/test_out.py:173: AssertionError
__________________ outTestsWithHackedStdout.test_print_list_with_title_success ___________________

self = <test_out.outTestsWithHackedStdout testMethod=test_print_list_with_title_success>

    def test_print_list_with_title_success(self):
        notes_list = '''=================== test ==================
    Found 2 items
      1 : 2004-09-16        2004-09-16        testnote
      2 : 2004-09-16        2004-09-16        testnote\n'''
        printList([NoteStub() for _ in xrange(2)], title='test')
        sys.stdout.seek(0)
>       self.assertEquals(sys.stdout.read(), notes_list)
E       AssertionError: '=================== test ==================\nFound 2 items\n  1 : 2004-09-15        2004-09-15        testnote\n  2 : 2004-09-15        2004-09-15        testnote\n' != '=================== test ==================\nFound 2 items\n  1 : 2004-09-16        2004-09-16        testnote\n  2 : 2004-09-16        2004-09-16        testnote\n'

tests/test_out.py:152: AssertionError
___________________ outTestsWithHackedStdout.test_print_list_with_urls_success ___________________

self = <test_out.outTestsWithHackedStdout testMethod=test_print_list_with_urls_success>

    def test_print_list_with_urls_success(self):
        notes_list = '''=================== test ==================
    Found 2 items
      1 : 2004-09-16        2004-09-16        testnote >>> https://www.evernote.com/Home.action?#n=12345
      2 : 2004-09-16        2004-09-16        testnote >>> https://www.evernote.com/Home.action?#n=12345
    '''
        printList([NoteStub() for _ in xrange(2)], title='test', showUrl=True)
        sys.stdout.seek(0)
>       self.assertEquals(sys.stdout.read(), notes_list)
E       AssertionError: '=================== test ==================\nFound 2 items\n  1 : 2004-09-15        2004-09-15        testnote >>> https://www.evernote.com/Home.action?#n=12345\n  2 : 2004-09-15        2004-09-15        testnote >>> https://www.evernote.com/Home.action?#n=12345\n' != '=================== test ==================\nFound 2 items\n  1 : 2004-09-16        2004-09-16        testnote >>> https://www.evernote.com/Home.action?#n=12345\n  2 : 2004-09-16        2004-09-16        testnote >>> https://www.evernote.com/Home.action?#n=12345\n'

tests/test_out.py:162: AssertionError
_________________ outTestsWithHackedStdout.test_print_list_without_title_success _________________

self = <test_out.outTestsWithHackedStdout testMethod=test_print_list_without_title_success>

    def test_print_list_without_title_success(self):
        notes_list = '''Found 2 items
      1 : 2004-09-16        2004-09-16        testnote
      2 : 2004-09-16        2004-09-16        testnote\n'''
        printList([NoteStub() for _ in xrange(2)])
        sys.stdout.seek(0)
>       self.assertEquals(sys.stdout.read(), notes_list)
E       AssertionError: 'Found 2 items\n  1 : 2004-09-15        2004-09-15        testnote\n  2 : 2004-09-15        2004-09-15        testnote\n' != 'Found 2 items\n  1 : 2004-09-16        2004-09-16        testnote\n  2 : 2004-09-16        2004-09-16        testnote\n'

tests/test_out.py:143: AssertionError
______________________ outTestsWithHackedStdout.test_search_result_success _______________________

self = <test_out.outTestsWithHackedStdout testMethod=test_search_result_success>

    def test_search_result_success(self):
        result = '''Search request: test
    Found 2 items
      1 : 2004-09-16        2004-09-16        testnote
      2 : 2004-09-16        2004-09-16        testnote\n'''
        SearchResult([NoteStub() for _ in xrange(2)], 'test')
        sys.stdout.seek(0)
>       self.assertEquals(sys.stdout.read(), result)
E       AssertionError: 'Search request: test\nFound 2 items\n  1 : 2004-09-15        2004-09-15        testnote\n  2 : 2004-09-15        2004-09-15        testnote\n' != 'Search request: test\nFound 2 items\n  1 : 2004-09-16        2004-09-16        testnote\n  2 : 2004-09-16        2004-09-16        testnote\n'

tests/test_out.py:182: AssertionError
________________________ outTestsWithHackedStdout.test_show_note_success _________________________

self = <test_out.outTestsWithHackedStdout testMethod=test_show_note_success>

    def test_show_note_success(self):
        note = '''################## TITLE ##################
    testnote
    =================== META ==================
    Created: 2004-09-16     \nUpdated: 2004-09-16     \n'''\
    '''|||||||||||||||| REMINDERS ||||||||||||||||
    Order: None Time: None Done: None
    ----------------- CONTENT -----------------
    Tags: tag1, tag2, tag3
    ##note content\n\n'''
        showNote(NoteStub())
        sys.stdout.seek(0)
>       self.assertEquals(sys.stdout.read(), note)
E       AssertionError: '################## TITLE ##################\ntestnote\n=================== META ==================\nCreated: 2004-09-15     \nUpdated: 2004-09-15     \n|||||||||||||||| REMINDERS ||||||||||||||||\nOrder: None Time: None Done: None\n----------------- CONTENT -----------------\nTags: tag1, tag2, tag3\n##note content\n\n' != '################## TITLE ##################\ntestnote\n=================== META ==================\nCreated: 2004-09-16     \nUpdated: 2004-09-16     \n|||||||||||||||| REMINDERS ||||||||||||||||\nOrder: None Time: None Done: None\n----------------- CONTENT -----------------\nTags: tag1, tag2, tag3\n##note content\n\n'

tests/test_out.py:135: AssertionError
============================== 7 failed, 89 passed in 6.28 seconds ===============================
david@db-mbp geeknote $
```

**Pull request merged**
